comparisons:
  - name: "amip-4deg-81yr"
    long_name: "AMIP 81-year"
    variables:
      - name: "TMP2m"
        scale: 1
        long_name: "2-meter temperature"
        units: "K"
      - name: "PRATEsfc"
        scale: 86400
        long_name: "surface precipitation rate"
        units: "mm/day"
    res_4deg:
      reference_run:
        job_name: "jeremym/shield-amip-4deg-reference-inference-81yr"
      runs:
        - job_name: "jeremym/shield-amip-4deg-ace2-inference-81yr-IC0"
        - job_name: "jeremym/shield-amip-4deg-ace2-inference-81yr-IC1"
        - job_name: "jeremym/shield-amip-4deg-ace2-inference-81yr-IC2"
    res_1deg:
      reference_run:
        job_name: "brianhenn/shield-amip-1deg-reference-inference-81yr"
      runs:
        - job_name: "brianhenn/shield-amip-1deg-ace2-inference-81yr-IC0"
        - job_name: "brianhenn/shield-amip-1deg-ace2-inference-81yr-IC1"
        - job_name: "brianhenn/shield-amip-1deg-ace2-inference-81yr-IC2"
    c24_reference_runs:
      - "brianhenn/shield-amip-c96-vs-c24-4deg-81yr-IC0"
      - "brianhenn/shield-amip-c96-vs-c24-4deg-81yr-IC1"
  - name: "amip-4deg-10yr"
    long_name: "AMIP 10-year"
    variables:
      - name: "TMP2m"
        scale: 1
        long_name: "2-meter temperature"
        units: "K"
      - name: "PRATEsfc"
        scale: 86400
        long_name: "surface precipitation rate"
        units: "mm/day"
    res_4deg:
      reference_run:
        job_name: "jeremym/shield-amip-4deg-reference-inference-10yr-2001"
      runs:
        - job_name: "jeremym/shield-amip-4deg-ace2-inference-10yr-RS4-IC0"
        - job_name: "jeremym/shield-amip-4deg-ace2-inference-10yr-RS4-IC1"
        - job_name: "jeremym/shield-amip-4deg-ace2-inference-10yr-RS4-IC2"
    res_1deg:
      reference_run:
        job_name: "brianhenn/shield-amip-1deg-reference-inference-10yr"
      runs:
        - job_name: "brianhenn/shield-amip-1deg-ace2-inference-10yr-IC0"
        - job_name: "brianhenn/shield-amip-1deg-ace2-inference-10yr-IC1"
        - job_name: "brianhenn/shield-amip-1deg-ace2-inference-10yr-IC2"
    c24_reference_runs:
      - "brianhenn/shield-amip-c96-vs-c24-4deg-10yr-IC0"
      - "brianhenn/shield-amip-c96-vs-c24-4deg-10yr-IC1"
